/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RacesRouteImport } from './routes/races'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as IndexRouteImport } from './routes/index'

const RacesRoute = RacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/races': typeof RacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/races': typeof RacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/races': typeof RacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/planner' | '/races'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planner' | '/races'
  id: '__root__' | '/' | '/planner' | '/races'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlannerRoute: typeof PlannerRoute
  RacesRoute: typeof RacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/races': {
      id: '/races'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlannerRoute: PlannerRoute,
  RacesRoute: RacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
